In [18]:
import torch
import numpy as np

In [19]:
vector = torch.tensor([1,2,3,4,5,6])
print(vector)
print(vector.dtype)

tensor([1, 2, 3, 4, 5, 6])
torch.int64


In [20]:
float_vector = torch.FloatTensor([1,2,3,4,5,6])
print(float_vector)
print(float_vector.dtype)

tensor([1., 2., 3., 4., 5., 6.])
torch.float32


In [21]:
vector.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [27]:
numpy_array = np.array([1, 2, 3, 4, 5])
tensor_convertion = torch.from_numpy(numpy_array)
print(tensor_convertion)
print(tensor_convertion.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor
