In [3]:
import torch

In [14]:
one_d = torch.arange(0, 9)
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [15]:
two_d = one_d.view(3,3)
print(two_d)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [21]:
three_d = torch.arange(18).view(3,2,3)
print(three_d)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])


In [27]:
three_d[1]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])