In [1]:
import torch

In [5]:
A = torch.tensor([0,3,5,5,5,2]).view(2,3)
print(A)

tensor([[0, 3, 5],
        [5, 5, 2]])


In [7]:
B = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
print(B)

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [12]:
C = torch.matmul(A, B) # A @ B
print(C)

tensor([[ 29, -16],
        [ 38,   6]])
